<?php
/**
 * AlertingAccessTokenResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AlertingAccessTokenResponse Class Doc Comment
 *
 * @category Class
 * @description Access token details
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AlertingAccessTokenResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AlertingAccessTokenResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'access_token_id' => 'string',
        'external_provider_name' => 'string',
        'external_user_email' => 'string',
        'external_account_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'access_token_id' => null,
        'external_provider_name' => null,
        'external_user_email' => null,
        'external_account_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_token_id' => 'access_token_id',
        'external_provider_name' => 'external_provider_name',
        'external_user_email' => 'external_user_email',
        'external_account_name' => 'external_account_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_token_id' => 'setAccessTokenId',
        'external_provider_name' => 'setExternalProviderName',
        'external_user_email' => 'setExternalUserEmail',
        'external_account_name' => 'setExternalAccountName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_token_id' => 'getAccessTokenId',
        'external_provider_name' => 'getExternalProviderName',
        'external_user_email' => 'getExternalUserEmail',
        'external_account_name' => 'getExternalAccountName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const EXTERNAL_PROVIDER_NAME_GITHUB = 'github';
    const EXTERNAL_PROVIDER_NAME_VSTS = 'vsts';
    const EXTERNAL_PROVIDER_NAME_JIRA = 'jira';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExternalProviderNameAllowableValues()
    {
        return [
            self::EXTERNAL_PROVIDER_NAME_GITHUB,
            self::EXTERNAL_PROVIDER_NAME_VSTS,
            self::EXTERNAL_PROVIDER_NAME_JIRA,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['access_token_id'] = isset($data['access_token_id']) ? $data['access_token_id'] : null;
        $this->container['external_provider_name'] = isset($data['external_provider_name']) ? $data['external_provider_name'] : null;
        $this->container['external_user_email'] = isset($data['external_user_email']) ? $data['external_user_email'] : null;
        $this->container['external_account_name'] = isset($data['external_account_name']) ? $data['external_account_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['access_token_id'] === null) {
            $invalidProperties[] = "'access_token_id' can't be null";
        }
        if ($this->container['external_provider_name'] === null) {
            $invalidProperties[] = "'external_provider_name' can't be null";
        }
        $allowedValues = $this->getExternalProviderNameAllowableValues();
        if (!is_null($this->container['external_provider_name']) && !in_array($this->container['external_provider_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'external_provider_name', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['external_user_email'] === null) {
            $invalidProperties[] = "'external_user_email' can't be null";
        }
        if ($this->container['external_account_name'] === null) {
            $invalidProperties[] = "'external_account_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_token_id
     *
     * @return string
     */
    public function getAccessTokenId()
    {
        return $this->container['access_token_id'];
    }

    /**
     * Sets access_token_id
     *
     * @param string $access_token_id ID of the access token
     *
     * @return $this
     */
    public function setAccessTokenId($access_token_id)
    {
        $this->container['access_token_id'] = $access_token_id;

        return $this;
    }

    /**
     * Gets external_provider_name
     *
     * @return string
     */
    public function getExternalProviderName()
    {
        return $this->container['external_provider_name'];
    }

    /**
     * Sets external_provider_name
     *
     * @param string $external_provider_name External provider name
     *
     * @return $this
     */
    public function setExternalProviderName($external_provider_name)
    {
        $allowedValues = $this->getExternalProviderNameAllowableValues();
        if (!in_array($external_provider_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'external_provider_name', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['external_provider_name'] = $external_provider_name;

        return $this;
    }

    /**
     * Gets external_user_email
     *
     * @return string
     */
    public function getExternalUserEmail()
    {
        return $this->container['external_user_email'];
    }

    /**
     * Sets external_user_email
     *
     * @param string $external_user_email The email of external user that used to authenticate aginst the external oauth provider
     *
     * @return $this
     */
    public function setExternalUserEmail($external_user_email)
    {
        $this->container['external_user_email'] = $external_user_email;

        return $this;
    }

    /**
     * Gets external_account_name
     *
     * @return string
     */
    public function getExternalAccountName()
    {
        return $this->container['external_account_name'];
    }

    /**
     * Sets external_account_name
     *
     * @param string $external_account_name The account name of external user that used to authenticate against the external oauth provider or basic auth
     *
     * @return $this
     */
    public function setExternalAccountName($external_account_name)
    {
        $this->container['external_account_name'] = $external_account_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


