<?php
/**
 * InlineResponse20067FeaturesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20067FeaturesTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20067Features
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20067FeaturesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20067Features"
     */
    public function testInlineResponse20067Features()
    {
    }

    /**
     * Test attribute "crashgroup_modify_status"
     */
    public function testPropertyCrashgroupModifyStatus()
    {
    }

    /**
     * Test attribute "crashgroup_modify_annotation"
     */
    public function testPropertyCrashgroupModifyAnnotation()
    {
    }

    /**
     * Test attribute "search"
     */
    public function testPropertySearch()
    {
    }

    /**
     * Test attribute "crashgroup_analytics_crashfreeusers"
     */
    public function testPropertyCrashgroupAnalyticsCrashfreeusers()
    {
    }

    /**
     * Test attribute "crashgroup_analytics_impactedusers"
     */
    public function testPropertyCrashgroupAnalyticsImpactedusers()
    {
    }

    /**
     * Test attribute "crash_download_raw"
     */
    public function testPropertyCrashDownloadRaw()
    {
    }
}
