<?php
/**
 * InlineResponse20013Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ZeC128\AppCenter;

/**
 * InlineResponse20013Test Class Doc Comment
 *
 * @category    Class
 * @description Aggregated Billing Information for a user or an organization
 * @package     ZeC128\AppCenter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20013Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20013"
     */
    public function testInlineResponse20013()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "billing_plans"
     */
    public function testPropertyBillingPlans()
    {
    }

    /**
     * Test attribute "usage"
     */
    public function testPropertyUsage()
    {
    }

    /**
     * Test attribute "azure_subscription_id"
     */
    public function testPropertyAzureSubscriptionId()
    {
    }

    /**
     * Test attribute "azure_subscription_state"
     */
    public function testPropertyAzureSubscriptionState()
    {
    }
}
