<?php
/**
 * MemberDevicesInfoResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MemberDevicesInfoResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The information for a single distribution group member and their ios device
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MemberDevicesInfoResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MemberDevicesInfoResponse"
     */
    public function testMemberDevicesInfoResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {
    }

    /**
     * Test attribute "can_change_password"
     */
    public function testPropertyCanChangePassword()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "invite_pending"
     */
    public function testPropertyInvitePending()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "udid"
     */
    public function testPropertyUdid()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "device_name"
     */
    public function testPropertyDeviceName()
    {
    }

    /**
     * Test attribute "full_device_name"
     */
    public function testPropertyFullDeviceName()
    {
    }

    /**
     * Test attribute "os_build"
     */
    public function testPropertyOsBuild()
    {
    }

    /**
     * Test attribute "os_version"
     */
    public function testPropertyOsVersion()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "imei"
     */
    public function testPropertyImei()
    {
    }

    /**
     * Test attribute "owner_id"
     */
    public function testPropertyOwnerId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "registered_at"
     */
    public function testPropertyRegisteredAt()
    {
    }
}
