<?php
/**
 * PatchReleaseRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ZeC128\AppCenter;

/**
 * PatchReleaseRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PatchReleaseRequest
 * @package     ZeC128\AppCenter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PatchReleaseRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PatchReleaseRequest"
     */
    public function testPatchReleaseRequest()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "dest_publish_id"
     */
    public function testPropertyDestPublishId()
    {
    }

    /**
     * Test attribute "error_details"
     */
    public function testPropertyErrorDetails()
    {
    }

    /**
     * Test attribute "error_context_id"
     */
    public function testPropertyErrorContextId()
    {
    }

    /**
     * Test attribute "wrap_package_url"
     */
    public function testPropertyWrapPackageUrl()
    {
    }

    /**
     * Test attribute "is_wrapper_request"
     */
    public function testPropertyIsWrapperRequest()
    {
    }
}
