<?php
/**
 * PrivateBasicReleaseDetailsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PrivateBasicReleaseDetailsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Basic information on a release for private apis
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PrivateBasicReleaseDetailsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PrivateBasicReleaseDetailsResponse"
     */
    public function testPrivateBasicReleaseDetailsResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "short_version"
     */
    public function testPropertyShortVersion()
    {
    }

    /**
     * Test attribute "uploaded_at"
     */
    public function testPropertyUploadedAt()
    {
    }

    /**
     * Test attribute "distribution_group_id"
     */
    public function testPropertyDistributionGroupId()
    {
    }

    /**
     * Test attribute "destination_type"
     */
    public function testPropertyDestinationType()
    {
    }

    /**
     * Test attribute "is_latest"
     */
    public function testPropertyIsLatest()
    {
    }

    /**
     * Test attribute "mandatory_update"
     */
    public function testPropertyMandatoryUpdate()
    {
    }

    /**
     * Test attribute "publishing_status"
     */
    public function testPropertyPublishingStatus()
    {
    }

    /**
     * Test attribute "is_external_build"
     */
    public function testPropertyIsExternalBuild()
    {
    }
}
