<?php
/**
 * ReleaseDetailsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReleaseDetailsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Details of an uploaded release
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReleaseDetailsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReleaseDetailsResponse"
     */
    public function testReleaseDetailsResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "app_name"
     */
    public function testPropertyAppName()
    {
    }

    /**
     * Test attribute "app_display_name"
     */
    public function testPropertyAppDisplayName()
    {
    }

    /**
     * Test attribute "app_os"
     */
    public function testPropertyAppOs()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
    }

    /**
     * Test attribute "short_version"
     */
    public function testPropertyShortVersion()
    {
    }

    /**
     * Test attribute "release_notes"
     */
    public function testPropertyReleaseNotes()
    {
    }

    /**
     * Test attribute "provisioning_profile_name"
     */
    public function testPropertyProvisioningProfileName()
    {
    }

    /**
     * Test attribute "provisioning_profile_type"
     */
    public function testPropertyProvisioningProfileType()
    {
    }

    /**
     * Test attribute "provisioning_profile_expiry_date"
     */
    public function testPropertyProvisioningProfileExpiryDate()
    {
    }

    /**
     * Test attribute "is_provisioning_profile_syncing"
     */
    public function testPropertyIsProvisioningProfileSyncing()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "min_os"
     */
    public function testPropertyMinOs()
    {
    }

    /**
     * Test attribute "device_family"
     */
    public function testPropertyDeviceFamily()
    {
    }

    /**
     * Test attribute "android_min_api_level"
     */
    public function testPropertyAndroidMinApiLevel()
    {
    }

    /**
     * Test attribute "bundle_identifier"
     */
    public function testPropertyBundleIdentifier()
    {
    }

    /**
     * Test attribute "package_hashes"
     */
    public function testPropertyPackageHashes()
    {
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
    }

    /**
     * Test attribute "uploaded_at"
     */
    public function testPropertyUploadedAt()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }

    /**
     * Test attribute "app_icon_url"
     */
    public function testPropertyAppIconUrl()
    {
    }

    /**
     * Test attribute "install_url"
     */
    public function testPropertyInstallUrl()
    {
    }

    /**
     * Test attribute "destination_type"
     */
    public function testPropertyDestinationType()
    {
    }

    /**
     * Test attribute "distribution_groups"
     */
    public function testPropertyDistributionGroups()
    {
    }

    /**
     * Test attribute "distribution_stores"
     */
    public function testPropertyDistributionStores()
    {
    }

    /**
     * Test attribute "destinations"
     */
    public function testPropertyDestinations()
    {
    }

    /**
     * Test attribute "is_udid_provisioned"
     */
    public function testPropertyIsUdidProvisioned()
    {
    }

    /**
     * Test attribute "can_resign"
     */
    public function testPropertyCanResign()
    {
    }

    /**
     * Test attribute "build"
     */
    public function testPropertyBuild()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "is_external_build"
     */
    public function testPropertyIsExternalBuild()
    {
    }
}
