<?php
/**
 * TestReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ZeC128\AppCenter;

/**
 * TestReportTest Class Doc Comment
 *
 * @category    Class
 * @description TestReport
 * @package     ZeC128\AppCenter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TestReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TestReport"
     */
    public function testTestReport()
    {
    }

    /**
     * Test attribute "app_upload_id"
     */
    public function testPropertyAppUploadId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "test_type"
     */
    public function testPropertyTestType()
    {
    }

    /**
     * Test attribute "platform"
     */
    public function testPropertyPlatform()
    {
    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "schema_version"
     */
    public function testPropertySchemaVersion()
    {
    }

    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {
    }

    /**
     * Test attribute "finished_device_snapshots"
     */
    public function testPropertyFinishedDeviceSnapshots()
    {
    }

    /**
     * Test attribute "device_logs"
     */
    public function testPropertyDeviceLogs()
    {
    }

    /**
     * Test attribute "date_finished"
     */
    public function testPropertyDateFinished()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "snapshot_fatal_errors"
     */
    public function testPropertySnapshotFatalErrors()
    {
    }
}
