<?php
/**
 * XcodeToolsetSharedSchemesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ZeC128\AppCenter;

/**
 * XcodeToolsetSharedSchemesTest Class Doc Comment
 *
 * @category    Class
 * @description XcodeToolsetSharedSchemes
 * @package     ZeC128\AppCenter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class XcodeToolsetSharedSchemesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "XcodeToolsetSharedSchemes"
     */
    public function testXcodeToolsetSharedSchemes()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "has_test_action"
     */
    public function testPropertyHasTestAction()
    {
    }

    /**
     * Test attribute "archive_configuration"
     */
    public function testPropertyArchiveConfiguration()
    {
    }

    /**
     * Test attribute "archive_project"
     */
    public function testPropertyArchiveProject()
    {
    }
}
