<?php
/**
 * XcodeBranchConfigurationPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ZeC128\AppCenter;

/**
 * XcodeBranchConfigurationPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description Build configuration when Xcode is part of the build steps
 * @package     ZeC128\AppCenter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class XcodeBranchConfigurationPropertiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "XcodeBranchConfigurationProperties"
     */
    public function testXcodeBranchConfigurationProperties()
    {
    }

    /**
     * Test attribute "project_or_workspace_path"
     */
    public function testPropertyProjectOrWorkspacePath()
    {
    }

    /**
     * Test attribute "podfile_path"
     */
    public function testPropertyPodfilePath()
    {
    }

    /**
     * Test attribute "cartfile_path"
     */
    public function testPropertyCartfilePath()
    {
    }

    /**
     * Test attribute "provisioning_profile_encoded"
     */
    public function testPropertyProvisioningProfileEncoded()
    {
    }

    /**
     * Test attribute "certificate_encoded"
     */
    public function testPropertyCertificateEncoded()
    {
    }

    /**
     * Test attribute "provisioning_profile_file_id"
     */
    public function testPropertyProvisioningProfileFileId()
    {
    }

    /**
     * Test attribute "certificate_file_id"
     */
    public function testPropertyCertificateFileId()
    {
    }

    /**
     * Test attribute "provisioning_profile_upload_id"
     */
    public function testPropertyProvisioningProfileUploadId()
    {
    }

    /**
     * Test attribute "app_extension_provisioning_profile_files"
     */
    public function testPropertyAppExtensionProvisioningProfileFiles()
    {
    }

    /**
     * Test attribute "certificate_upload_id"
     */
    public function testPropertyCertificateUploadId()
    {
    }

    /**
     * Test attribute "certificate_password"
     */
    public function testPropertyCertificatePassword()
    {
    }

    /**
     * Test attribute "scheme"
     */
    public function testPropertyScheme()
    {
    }

    /**
     * Test attribute "xcode_version"
     */
    public function testPropertyXcodeVersion()
    {
    }

    /**
     * Test attribute "provisioning_profile_filename"
     */
    public function testPropertyProvisioningProfileFilename()
    {
    }

    /**
     * Test attribute "certificate_filename"
     */
    public function testPropertyCertificateFilename()
    {
    }

    /**
     * Test attribute "team_id"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "automatic_signing"
     */
    public function testPropertyAutomaticSigning()
    {
    }

    /**
     * Test attribute "xcode_project_sha"
     */
    public function testPropertyXcodeProjectSha()
    {
    }

    /**
     * Test attribute "archive_configuration"
     */
    public function testPropertyArchiveConfiguration()
    {
    }

    /**
     * Test attribute "target_to_archive"
     */
    public function testPropertyTargetToArchive()
    {
    }

    /**
     * Test attribute "force_legacy_build_system"
     */
    public function testPropertyForceLegacyBuildSystem()
    {
    }
}
