<?php
/**
 * ErrorsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ErrorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ErrorsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for errorsAppBuildsList
     *
     * .
     *
     */
    public function testErrorsAppBuildsList()
    {
    }

    /**
     * Test case for errorsAvailableVersions
     *
     * .
     *
     */
    public function testErrorsAvailableVersions()
    {
    }

    /**
     * Test case for errorsCountsPerDay
     *
     * .
     *
     */
    public function testErrorsCountsPerDay()
    {
    }

    /**
     * Test case for errorsDeleteError
     *
     * .
     *
     */
    public function testErrorsDeleteError()
    {
    }

    /**
     * Test case for errorsErrorAttachmentLocation
     *
     * .
     *
     */
    public function testErrorsErrorAttachmentLocation()
    {
    }

    /**
     * Test case for errorsErrorAttachmentText
     *
     * .
     *
     */
    public function testErrorsErrorAttachmentText()
    {
    }

    /**
     * Test case for errorsErrorAttachments
     *
     * .
     *
     */
    public function testErrorsErrorAttachments()
    {
    }

    /**
     * Test case for errorsErrorDownload
     *
     * .
     *
     */
    public function testErrorsErrorDownload()
    {
    }

    /**
     * Test case for errorsErrorFreeDevicePercentages
     *
     * .
     *
     */
    public function testErrorsErrorFreeDevicePercentages()
    {
    }

    /**
     * Test case for errorsErrorGroupsSearch
     *
     * .
     *
     */
    public function testErrorsErrorGroupsSearch()
    {
    }

    /**
     * Test case for errorsErrorLocation
     *
     * .
     *
     */
    public function testErrorsErrorLocation()
    {
    }

    /**
     * Test case for errorsErrorSearch
     *
     * .
     *
     */
    public function testErrorsErrorSearch()
    {
    }

    /**
     * Test case for errorsErrorStackTrace
     *
     * .
     *
     */
    public function testErrorsErrorStackTrace()
    {
    }

    /**
     * Test case for errorsGetErrorDetails
     *
     * .
     *
     */
    public function testErrorsGetErrorDetails()
    {
    }

    /**
     * Test case for errorsGetRetentionSettings
     *
     * gets the retention settings in days.
     *
     */
    public function testErrorsGetRetentionSettings()
    {
    }

    /**
     * Test case for errorsGroupCountsPerDay
     *
     * .
     *
     */
    public function testErrorsGroupCountsPerDay()
    {
    }

    /**
     * Test case for errorsGroupDetails
     *
     * .
     *
     */
    public function testErrorsGroupDetails()
    {
    }

    /**
     * Test case for errorsGroupErrorFreeDevicePercentages
     *
     * .
     *
     */
    public function testErrorsGroupErrorFreeDevicePercentages()
    {
    }

    /**
     * Test case for errorsGroupErrorStackTrace
     *
     * .
     *
     */
    public function testErrorsGroupErrorStackTrace()
    {
    }

    /**
     * Test case for errorsGroupList
     *
     * .
     *
     */
    public function testErrorsGroupList()
    {
    }

    /**
     * Test case for errorsGroupModelCounts
     *
     * .
     *
     */
    public function testErrorsGroupModelCounts()
    {
    }

    /**
     * Test case for errorsGroupOperatingSystemCounts
     *
     * .
     *
     */
    public function testErrorsGroupOperatingSystemCounts()
    {
    }

    /**
     * Test case for errorsLatestErrorDetails
     *
     * .
     *
     */
    public function testErrorsLatestErrorDetails()
    {
    }

    /**
     * Test case for errorsListForGroup
     *
     * .
     *
     */
    public function testErrorsListForGroup()
    {
    }

    /**
     * Test case for errorsListSessionLogs
     *
     * .
     *
     */
    public function testErrorsListSessionLogs()
    {
    }

    /**
     * Test case for errorsPutRetentionSettings
     *
     * Creates and updates the retention settings in days.
     *
     */
    public function testErrorsPutRetentionSettings()
    {
    }

    /**
     * Test case for errorsUpdateState
     *
     * .
     *
     */
    public function testErrorsUpdateState()
    {
    }
}
