<?php
/**
 * PushApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PushApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PushApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for pushConfigExists
     *
     * .
     *
     */
    public function testPushConfigExists()
    {
    }

    /**
     * Test case for pushDelete
     *
     * .
     *
     */
    public function testPushDelete()
    {
    }

    /**
     * Test case for pushDeleteConfig
     *
     * .
     *
     */
    public function testPushDeleteConfig()
    {
    }

    /**
     * Test case for pushDeleteInstallId
     *
     * .
     *
     */
    public function testPushDeleteInstallId()
    {
    }

    /**
     * Test case for pushExportDevices
     *
     * .
     *
     */
    public function testPushExportDevices()
    {
    }

    /**
     * Test case for pushExportDevicesStatus
     *
     * .
     *
     */
    public function testPushExportDevicesStatus()
    {
    }

    /**
     * Test case for pushGet
     *
     * .
     *
     */
    public function testPushGet()
    {
    }

    /**
     * Test case for pushGetConfig
     *
     * .
     *
     */
    public function testPushGetConfig()
    {
    }

    /**
     * Test case for pushList
     *
     * .
     *
     */
    public function testPushList()
    {
    }

    /**
     * Test case for pushSend
     *
     * .
     *
     */
    public function testPushSend()
    {
    }

    /**
     * Test case for pushSetConfig
     *
     * .
     *
     */
    public function testPushSetConfig()
    {
    }
}
