<?php
/**
 * V2MissingSymbolCrashGroupStatusEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ZeC128\AppCenter\AppCenterApi;
use \ZeC128\AppCenter\ObjectSerializer;

/**
 * V2MissingSymbolCrashGroupStatusEnum Class Doc Comment
 *
 * @category Class
 * @description enumeration of missing symbol grash group statuses
 * @package  ZeC128\AppCenter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V2MissingSymbolCrashGroupStatusEnum
{
    /**
     * Possible values of this enum
     */
    const ACTIVE = 'active';
    const PENDING = 'pending';
    const CLOSED = 'closed';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::PENDING,
            self::CLOSED,
        ];
    }
}


